# Generated by Django 6.0.1 on 2026-01-23 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffirmationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Affirmation Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('great', 'Great 😊'), ('good', 'Good 🙂'), ('okay', 'Okay 😐'), ('struggling', 'Struggling 😔'), ('difficult', 'Very Difficult 😢')], max_length=20, unique=True)),
                ('color', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Mood Categories',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('book', 'Book'), ('website', 'Website'), ('hotline', 'Crisis Hotline'), ('app', 'Mobile App')], max_length=20)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, help_text='For hotlines', max_length=50)),
                ('is_crisis_support', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_crisis_support', '-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affirmations', to='hope_healing.affirmationcategory')),
            ],
            options={
                'ordering': ['?'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Anonymous', help_text='How you want to appear (optional)', max_length=50)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='hope_healing.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('morning_mood', models.CharField(blank=True, choices=[('great', 'Great 😊'), ('good', 'Good 🙂'), ('okay', 'Okay 😐'), ('struggling', 'Struggling 😔'), ('difficult', 'Very Difficult 😢')], help_text='How are you feeling this morning?', max_length=20)),
                ('evening_mood', models.CharField(blank=True, choices=[('great', 'Great 😊'), ('good', 'Good 🙂'), ('okay', 'Okay 😐'), ('struggling', 'Struggling 😔'), ('difficult', 'Very Difficult 😢')], help_text='How are you feeling this evening?', max_length=20)),
                ('prayed', models.BooleanField(default=False, help_text='Did you pray today?')),
                ('meditated', models.BooleanField(default=False, help_text='Did you meditate today?')),
                ('read_scripture', models.BooleanField(default=False, help_text='Did you read spiritual texts?')),
                ('meditation_minutes', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Any reflections for today?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('entry', models.TextField(help_text='What are you grateful for today?')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gratitude Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('meditation', 'Meditation'), ('prayer', 'Prayer'), ('breathing', 'Breathing Exercise')], default='meditation', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-created_date'], name='hope_healin_created_931701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitypostlike',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='dailycheckin',
            index=models.Index(fields=['user', '-date'], name='hope_healin_user_id_8a49a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycheckin',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='gratitudeentry',
            index=models.Index(fields=['user', '-date'], name='hope_healin_user_id_5624cb_idx'),
        ),
        migrations.AddIndex(
            model_name='meditationsession',
            index=models.Index(fields=['user', '-date'], name='hope_healin_user_id_5b1c2c_idx'),
        ),
    ]
